# **Introducción a Pandas**

Pandas es una librería de Python diseñada para **análisis y manipulación de datos**.  
Su nombre viene de *Panel Data* y se ha convertido en una de las herramientas más usadas en ciencia de datos.

## Objetos principales

- **Series**: estructura unidimensional (similar a un array con etiquetas).
- **DataFrame**: estructura bidimensional (tabla con filas y columnas).
- **Index**: etiquetas que identifican filas y columnas.

Pandas es como una **navaja suiza para datos**: permite leer, limpiar, transformar, analizar y visualizar información de manera sencilla y eficiente.

In [1]:
import pandas as pd

### Diferencia entre `pd.Series` y `pd.DataFrame` en pandas

En **pandas**, una **Series** y un **DataFrame** son estructuras de datos distintas:

**Series**
- Es una estructura **unidimensional (1D)**.
- Representa una sola variable o columna.
- Tiene un **índice** y un conjunto de valores.
- Es equivalente a una columna de una tabla.

**DataFrame**
- Es una estructura **bidimensional (2D)**.
- Representa una **tabla de datos** con filas y columnas.
- Cada columna del DataFrame es una **Series**.
- Puede contener múltiples variables con distintos tipos de datos.

**Relación clave**
- `df["columna"]` devuelve una **Series**.
- `df[["columna"]]` devuelve un **DataFrame** con una sola columna.

**Resumen**
- Usa **Series** para trabajar con una sola variable.
- Usa **DataFrame** para analizar conjuntos de variables y sus relaciones.
---

## 0. Métodos de lista

In [2]:
# Append
numbers = [1, 2, 3]
numbers.append(4)
print(numbers)

[1, 2, 3, 4]

In [3]:
# Extend
numbers = [1, 2, 3]
numbers.extend([4, 5])
print(numbers)

[1, 2, 3, 4, 5]

In [4]:
# Insert
numbers = [1, 2, 4]
numbers.insert(2, 3)  # insert 3 at index 2
print(numbers)

[1, 2, 3, 4]

In [5]:
# Remove
numbers = [1, 2, 3, 2]
numbers.remove(2) 
print(numbers)

[1, 3, 2]

In [6]:
# Pop
numbers = [1, 2, 3]
last = numbers.pop()
print(last)
print(numbers)

3
[1, 2]

In [7]:
numbers = [1, 2, 3]
item = numbers.pop(0)
print(item)
print(numbers)

1
[2, 3]

In [8]:
# Clear
numbers = [1, 2, 3]
numbers.clear()
print(numbers)

[]

In [9]:
# Index
numbers = [10, 20, 30, 20]
pos = numbers.index(20)
print(pos)

1

In [10]:
# Rango
pos = numbers.index(20, 2)
print(pos)

3

In [11]:
# Count
numbers = [1, 2, 2, 3, 2]
print(numbers.count(2))

3

In [12]:
# Sort
numbers = [4, 1, 3, 2]
numbers.sort()
print(numbers)

[1, 2, 3, 4]

In [13]:
# Sort
numbers.sort(reverse=True)
print(numbers)

[4, 3, 2, 1]

In [14]:
# Sort con string
words = ["apple", "banana", "kiwi"]
words.sort(key=len)
print(words)

['kiwi', 'apple', 'banana']

In [15]:
# Reverse
numbers = [1, 2, 3]
numbers.reverse()
print(numbers)

[3, 2, 1]

In [16]:
# Copy
numbers = [1, 2, 3]
copy_numbers = numbers.copy()
copy_numbers.append(4)

print(numbers)
print(copy_numbers)

[1, 2, 3]
[1, 2, 3, 4]

In [17]:
# Listas
numbers = [1, 2, 3, 4]

print(len(numbers))   # length
print(min(numbers))   # minimum
print(max(numbers))   # maximum
print(sum(numbers))   # sum
print(sorted(numbers))  # new sorted list

4
1
4
10
[1, 2, 3, 4]

## 1. Creación de objetos

In [18]:
# Series: estructura unidimensional
serie = pd.Series([10, 20, 30], index=["a", "b", "c"])
print("Series:\n", serie)

Series:
 a    10
b    20
c    30
dtype: int64

In [19]:
# DataFrame: estructura tabular
df = pd.DataFrame({
      "Nombre": ["Ana", "Luis", "Carla"],
    "Edad": [23, 35, 29],
    "Ciudad": ["La Paz", "Cochabamba", "Santa Cruz"]
 })
print("\nDataFrame:\n", df)

DataFrame:
   Nombre  Edad      Ciudad
0    Ana    23      La Paz
1   Luis    35  Cochabamba
2  Carla    29  Santa Cruz

In [20]:
# Desde una lista de listas (con nombres de columnas)
df = pd.DataFrame(
    [["Ana", 23, "La Paz"],
     ["Luis", 35, "Cochabamba"],
     ["Carla", 29, "Santa Cruz"]],
    columns=["Nombre", "Edad", "Ciudad"]
)
print("\nDataFrame:\n", df)

DataFrame:
   Nombre  Edad      Ciudad
0    Ana    23      La Paz
1   Luis    35  Cochabamba
2  Carla    29  Santa Cruz

In [21]:
# Desde un diccionario de Series
df = pd.DataFrame({
    "Nombre": pd.Series(["Ana", "Luis", "Carla"]),
    "Edad": pd.Series([23, 35, 29]),
    "Ciudad": pd.Series(["La Paz", "Cochabamba", "Santa Cruz"])
})
print("\nDataFrame:\n", df)

DataFrame:
   Nombre  Edad      Ciudad
0    Ana    23      La Paz
1   Luis    35  Cochabamba
2  Carla    29  Santa Cruz

In [22]:
# Desde un array de NumPy
 
import numpy as np

data = np.array([
    ["Ana", 23, "La Paz"],
    ["Luis", 35, "Cochabamba"],
    ["Carla", 29, "Santa Cruz"]
])

df = pd.DataFrame(data, columns=["Nombre", "Edad", "Ciudad"])
print("\nDataFrame:\n", df)

DataFrame:
   Nombre Edad      Ciudad
0    Ana   23      La Paz
1   Luis   35  Cochabamba
2  Carla   29  Santa Cruz

In [23]:
# Importar datos desde un archivo CSV
ruta = r"F:\Users\ASUS\Desktop\ESAM\MAESTRIAS ESAM\GEM PERU\ESTADÍSTICA APLICADA A BANCA Y FINANZAS\clientes_aleatorio.csv"
df = pd.read_csv(ruta)
print("\nDataFrame desde CSV:\n", df)

DataFrame desde CSV:
       ID  Edad  IngresoMensual  GastosMensuales Genero   EstadoCivil  \
0      1    48            3283             2864      M      Casado/a
1      2    32            2428             1735      F       Viudo/a
2      3    68            2939             1056      M      Casado/a
3      4    31             763             2990      F     Soltero/a
4      5    20            1674              781      M     Soltero/a
..   ...   ...             ...              ...    ...           ...
195  196    63            3318             1157      F      Casado/a
196  197    38            1863              894      F      Casado/a
197  198    62            2247             2566      M  Divorciado/a
198  199    19            1222             1151      F     Soltero/a
199  200    60            4381              983      M     Soltero/a

         Ciudad  TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  \
0    Cochabamba                 True               True      Postgrado
1    Cochabamba                 True               True  Universitaria
2         Sucre                 True               True  Universitaria
3    Santa Cruz                False               True     Secundaria
4    Cochabamba                False               True       Primaria
..          ...                  ...                ...            ...
195  Santa Cruz                 True               True  Universitaria
196       Oruro                False              False       Primaria
197  Cochabamba                False              False     Secundaria
198      La Paz                False              False     Secundaria
199       Oruro                False               True     Secundaria

     NumeroComprasMes  PuntuacionFidelidad TipoCliente CanalPreferido  \
0                   7                  2.0     Regular       Teléfono
1                   3                 16.3     Regular         Online
2                  16                 89.6     Premium         Online
3                  19                 15.3         VIP         Online
4                   5                 25.9         VIP         Online
..                ...                  ...         ...            ...
195                 0                 19.7     Premium         Online
196                 3                 60.6     Regular       Teléfono
197                17                 97.5         VIP     Presencial
198                 3                 19.9     Regular     Presencial
199                 7                 43.5         VIP     Presencial

    ProductoFavorito
0                  C
1                  D
2                  B
3                  C
4                  B
..               ...
195                D
196                B
197                C
198                D
199                D

[200 rows x 15 columns]

Métodos de lista

## 2. Inspección de datos

In [24]:
# Head
print("\nPrimeras filas:\n", df.head(5))       # primeras filas

Primeras filas:
    ID  Edad  IngresoMensual  GastosMensuales Genero EstadoCivil      Ciudad  \
0   1    48            3283             2864      M    Casado/a  Cochabamba
1   2    32            2428             1735      F     Viudo/a  Cochabamba
2   3    68            2939             1056      M    Casado/a       Sucre
3   4    31             763             2990      F   Soltero/a  Santa Cruz
4   5    20            1674              781      M   Soltero/a  Cochabamba

   TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  NumeroComprasMes  \
0                 True               True      Postgrado                 7
1                 True               True  Universitaria                 3
2                 True               True  Universitaria                16
3                False               True     Secundaria                19
4                False               True       Primaria                 5

   PuntuacionFidelidad TipoCliente CanalPreferido ProductoFavorito
0                  2.0     Regular       Teléfono                C
1                 16.3     Regular         Online                D
2                 89.6     Premium         Online                B
3                 15.3         VIP         Online                C
4                 25.9         VIP         Online                B

In [25]:
# Tail
print("\nÚltimas filas:\n", df.tail(5))       # últimas filas

Últimas filas:
       ID  Edad  IngresoMensual  GastosMensuales Genero   EstadoCivil  \
195  196    63            3318             1157      F      Casado/a
196  197    38            1863              894      F      Casado/a
197  198    62            2247             2566      M  Divorciado/a
198  199    19            1222             1151      F     Soltero/a
199  200    60            4381              983      M     Soltero/a

         Ciudad  TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  \
195  Santa Cruz                 True               True  Universitaria
196       Oruro                False              False       Primaria
197  Cochabamba                False              False     Secundaria
198      La Paz                False              False     Secundaria
199       Oruro                False               True     Secundaria

     NumeroComprasMes  PuntuacionFidelidad TipoCliente CanalPreferido  \
195                 0                 19.7     Premium         Online
196                 3                 60.6     Regular       Teléfono
197                17                 97.5         VIP     Presencial
198                 3                 19.9     Regular     Presencial
199                 7                 43.5         VIP     Presencial

    ProductoFavorito
195                D
196                B
197                C
198                D
199                D

In [26]:
# Info
print("\nInformación general:\n")
df.info()

Información general:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   200 non-null    int64
 1   Edad                 200 non-null    int64
 2   IngresoMensual       200 non-null    int64
 3   GastosMensuales      200 non-null    int64
 4   Genero               200 non-null    object
 5   EstadoCivil          200 non-null    object
 6   Ciudad               200 non-null    object
 7   TieneTarjetaCredito  200 non-null    bool
 8   TieneCuentaAhorro    200 non-null    bool
 9   NivelEducacion       200 non-null    object
 10  NumeroComprasMes     200 non-null    int64
 11  PuntuacionFidelidad  200 non-null    float64
 12  TipoCliente          200 non-null    object
 13  CanalPreferido       200 non-null    object
 14  ProductoFavorito     200 non-null    object
dtypes: bool(2), float64(1), int64(5), object(7)
memory usage: 20.8+ KB

In [27]:
# Convertir tipo de dato
df["ID"] = df["ID"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   200 non-null    object
 1   Edad                 200 non-null    int64
 2   IngresoMensual       200 non-null    int64
 3   GastosMensuales      200 non-null    int64
 4   Genero               200 non-null    object
 5   EstadoCivil          200 non-null    object
 6   Ciudad               200 non-null    object
 7   TieneTarjetaCredito  200 non-null    bool
 8   TieneCuentaAhorro    200 non-null    bool
 9   NivelEducacion       200 non-null    object
 10  NumeroComprasMes     200 non-null    int64
 11  PuntuacionFidelidad  200 non-null    float64
 12  TipoCliente          200 non-null    object
 13  CanalPreferido       200 non-null    object
 14  ProductoFavorito     200 non-null    object
dtypes: bool(2), float64(1), int64(4), object(8)
memory usage: 20.8+ KB

In [28]:
# Convertir a numérico
df["IngresoMensual"] = df["IngresoMensual"].astype(str)
print("Convertido a str mediante astype:", df["IngresoMensual"].dtype)
df["IngresoMensual"] = pd.to_numeric(df["IngresoMensual"])
print("Reconvertido a numérico:", df["IngresoMensual"].dtype)

Convertido a str mediante astype: object
Reconvertido a numérico: int64

In [29]:
# Convertir columnas a tipo categórico
cols_categoricas = [
    "Genero", "EstadoCivil", "Ciudad",
    "NivelEducacion", "TipoCliente",
    "CanalPreferido", "ProductoFavorito"
]

df[cols_categoricas] = df[cols_categoricas].astype("category")

print(df[cols_categoricas].dtypes)

Genero              category
EstadoCivil         category
Ciudad              category
NivelEducacion      category
TipoCliente         category
CanalPreferido      category
ProductoFavorito    category
dtype: object

In [30]:
# Convertir columnas a tipo numérico float
cols_numericas = [
    "Edad", "IngresoMensual", "GastosMensuales",
    "NumeroComprasMes"
]

df[cols_numericas] = df[cols_numericas].astype(float)

In [31]:
# Crear nueva columna basada en condición
df["ClienteActivo"] = df["NumeroComprasMes"] >= 10
df["ClienteActivo"] = df["ClienteActivo"].astype("category")

In [32]:
# One-Hot Encoding: convierte variables categóricas en columnas binarias (0/1)
df_dummies = pd.get_dummies(
    
    df,  # DataFrame original que contiene las variables categóricas
    
    columns=["Genero", "EstadoCivil", "TipoCliente"],  
    # Lista de columnas categóricas que serán transformadas en variables dummy
    
    drop_first=True  
    # Elimina la primera categoría de cada variable para evitar multicolinealidad
    # (problema de la "dummy variable trap" en modelos estadísticos)
)

# Muestra las primeras filas del nuevo DataFrame con las variables dummy creadas
print("\nDataFrame con dummies:\n", df_dummies.head())

DataFrame con dummies:
   ID  Edad  IngresoMensual  GastosMensuales      Ciudad  TieneTarjetaCredito  \
0  1  48.0          3283.0           2864.0  Cochabamba                 True
1  2  32.0          2428.0           1735.0  Cochabamba                 True
2  3  68.0          2939.0           1056.0       Sucre                 True
3  4  31.0           763.0           2990.0  Santa Cruz                False
4  5  20.0          1674.0            781.0  Cochabamba                False

   TieneCuentaAhorro NivelEducacion  NumeroComprasMes  PuntuacionFidelidad  \
0               True      Postgrado               7.0                  2.0
1               True  Universitaria               3.0                 16.3
2               True  Universitaria              16.0                 89.6
3               True     Secundaria              19.0                 15.3
4               True       Primaria               5.0                 25.9

  CanalPreferido ProductoFavorito ClienteActivo  Genero_M  \
0       Teléfono                C         False      True
1         Online                D         False     False
2         Online                B          True      True
3         Online                C          True     False
4         Online                B         False      True

   EstadoCivil_Divorciado/a  EstadoCivil_Soltero/a  EstadoCivil_Viudo/a  \
0                     False                  False                False
1                     False                  False                 True
2                     False                  False                False
3                     False                   True                False
4                     False                   True                False

   TipoCliente_Regular  TipoCliente_VIP
0                 True            False
1                 True            False
2                False            False
3                False             True
4                False             True

In [33]:
# Descripción estadística
print("\nDescripción estadística:\n", df_dummies[["Edad", "IngresoMensual", "GastosMensuales"]].describe())  # estadísticas

Descripción estadística:
              Edad  IngresoMensual  GastosMensuales
count  200.000000      200.000000       200.000000
mean    45.090000     2689.375000      1560.860000
std     14.742067     1318.159298       863.795801
min     18.000000      528.000000       101.000000
25%     32.000000     1528.000000       825.000000
50%     44.000000     2595.000000      1576.500000
75%     58.250000     3838.500000      2353.500000
max     70.000000     4997.000000      2990.000000

## 3. Selección y filtrado

In [34]:
# Selección de columnas
print("\nColumna Edad:\n", df["Edad"])        # seleccionar columna

Columna Edad:
 0      48.0
1      32.0
2      68.0
3      31.0
4      20.0
       ...
195    63.0
196    38.0
197    62.0
198    19.0
199    60.0
Name: Edad, Length: 200, dtype: float64

In [35]:
# Selección por posición e índice
print("\nFila por índice loc:\n", df.loc[1])  # selección por etiqueta del índice

Fila por índice loc:
 ID                                 2
Edad                            32.0
IngresoMensual                2428.0
GastosMensuales               1735.0
Genero                             F
EstadoCivil                  Viudo/a
Ciudad                    Cochabamba
TieneTarjetaCredito             True
TieneCuentaAhorro               True
NivelEducacion         Universitaria
NumeroComprasMes                 3.0
PuntuacionFidelidad             16.3
TipoCliente                  Regular
CanalPreferido                Online
ProductoFavorito                   D
ClienteActivo                  False
Name: 1, dtype: object

In [36]:
# Seleccionar las filas con ID 196 a 199 y algunas columnas
df.loc[195:199, ["Edad", "IngresoMensual", "Ciudad"]]

     Edad  IngresoMensual      Ciudad
195  63.0          3318.0  Santa Cruz
196  38.0          1863.0       Oruro
197  62.0          2247.0  Cochabamba
198  19.0          1222.0      La Paz
199  60.0          4381.0       Oruro

In [37]:
    print("\nFila por posición iloc:\n", df.iloc[0]) # selección por posición del dato

Fila por posición iloc:
 ID                              1
Edad                         48.0
IngresoMensual             3283.0
GastosMensuales            2864.0
Genero                          M
EstadoCivil              Casado/a
Ciudad                 Cochabamba
TieneTarjetaCredito          True
TieneCuentaAhorro            True
NivelEducacion          Postgrado
NumeroComprasMes              7.0
PuntuacionFidelidad           2.0
TipoCliente               Regular
CanalPreferido           Teléfono
ProductoFavorito                C
ClienteActivo               False
Name: 0, dtype: object

In [38]:
# Últimas 5 filas y primeras 4 columnas
df.iloc[-5:, :4]
# El signo negativo significa contar desde el final.

      ID  Edad  IngresoMensual  GastosMensuales
195  196  63.0          3318.0           1157.0
196  197  38.0          1863.0            894.0
197  198  62.0          2247.0           2566.0
198  199  19.0          1222.0           1151.0
199  200  60.0          4381.0            983.0

In [39]:
# Filtrado de datos con condiciones
print("\nFiltrado:\n", df[df["Edad"] > 25])   # condición booleana

Filtrado:
       ID  Edad  IngresoMensual  GastosMensuales Genero   EstadoCivil  \
0      1  48.0          3283.0           2864.0      M      Casado/a
1      2  32.0          2428.0           1735.0      F       Viudo/a
2      3  68.0          2939.0           1056.0      M      Casado/a
3      4  31.0           763.0           2990.0      F     Soltero/a
5      6  59.0          2287.0           1877.0      M       Viudo/a
..   ...   ...             ...              ...    ...           ...
193  194  28.0          1949.0           1193.0      M  Divorciado/a
195  196  63.0          3318.0           1157.0      F      Casado/a
196  197  38.0          1863.0            894.0      F      Casado/a
197  198  62.0          2247.0           2566.0      M  Divorciado/a
199  200  60.0          4381.0            983.0      M     Soltero/a

         Ciudad  TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  \
0    Cochabamba                 True               True      Postgrado
1    Cochabamba                 True               True  Universitaria
2         Sucre                 True               True  Universitaria
3    Santa Cruz                False               True     Secundaria
5    Cochabamba                 True              False  Universitaria
..          ...                  ...                ...            ...
193  Santa Cruz                False              False  Universitaria
195  Santa Cruz                 True               True  Universitaria
196       Oruro                False              False       Primaria
197  Cochabamba                False              False     Secundaria
199       Oruro                False               True     Secundaria

     NumeroComprasMes  PuntuacionFidelidad TipoCliente CanalPreferido  \
0                 7.0                  2.0     Regular       Teléfono
1                 3.0                 16.3     Regular         Online
2                16.0                 89.6     Premium         Online
3                19.0                 15.3         VIP         Online
5                 6.0                 24.4         VIP       Teléfono
..                ...                  ...         ...            ...
193               7.0                 64.1     Regular       Teléfono
195               0.0                 19.7     Premium         Online
196               3.0                 60.6     Regular       Teléfono
197              17.0                 97.5         VIP     Presencial
199               7.0                 43.5         VIP     Presencial

    ProductoFavorito ClienteActivo
0                  C         False
1                  D         False
2                  B          True
3                  C          True
5                  A         False
..               ...           ...
193                B         False
195                D         False
196                B         False
197                C          True
199                D         False

[175 rows x 16 columns]

In [40]:
# Ingreso mensual de la persona con índice 199
df.at[199, "IngresoMensual"]

np.float64(4381.0)

In [41]:
# Valor en fila 199 (posición), columna 2 (IngresoMensual)
df.iat[199, 2]

np.float64(4381.0)

In [42]:
# Columnas que contienen la palabra "Tiene"
df.filter(like="Tiene")

### Parámetros principales de `df.filter`
"""
- items: selecciona nombres exactos de filas o columnas.  
  Ejemplo: `df.filter(items=['A', 'B'])` → columnas `'A'` y `'B'`.

- like: selecciona filas o columnas que contengan una subcadena (sensible a mayúsculas/minúsculas).  
  Ejemplo: `df.filter(like='Tiene')` → columnas con `"Tiene"` en su nombre.

- regex: selecciona filas o columnas que coincidan con una expresión regular.  
  Ejemplo: `df.filter(regex='^A.*')` → columnas que empiezan con `"A"`.

- axis: indica el eje sobre el que aplicar el filtro.  
  - `axis=0` → filas  
  - `axis=1` → columnas (por defecto)
"""

'\n- items: selecciona nombres exactos de filas o columnas.  \n  Ejemplo: `df.filter(items=[\'A\', \'B\'])` → columnas `\'A\'` y `\'B\'`.\n\n- like: selecciona filas o columnas que contengan una subcadena (sensible a mayúsculas/minúsculas).  \n  Ejemplo: `df.filter(like=\'Tiene\')` → columnas con `"Tiene"` en su nombre.\n\n- regex: selecciona filas o columnas que coincidan con una expresión regular.  \n  Ejemplo: `df.filter(regex=\'^A.*\')` → columnas que empiezan con `"A"`.\n\n- axis: indica el eje sobre el que aplicar el filtro.  \n  - `axis=0` → filas  \n  - `axis=1` → columnas (por defecto)\n'

In [43]:
# Selección de columnas específicas
df.filter(items=["Edad", "Genero", "Ciudad"])

     Edad Genero      Ciudad
0    48.0      M  Cochabamba
1    32.0      F  Cochabamba
2    68.0      M       Sucre
3    31.0      F  Santa Cruz
4    20.0      M  Cochabamba
..    ...    ...         ...
195  63.0      F  Santa Cruz
196  38.0      F       Oruro
197  62.0      M  Cochabamba
198  19.0      F      La Paz
199  60.0      M       Oruro

[200 rows x 3 columns]

In [44]:
# Selección por tipo de dato: numérico
df_numerico = df.select_dtypes(include=['number'])
print("\nDataFrame numérico:\n", df_numerico)

### Parámetros principales de `df.select_dtypes`
"""
- include: especifica los tipos de datos que quieres incluir.  
  Puede ser:
  - Una cadena: `'number'`, `'object'`, `'float'`, `'int'`, `'bool'`, `'datetime'`, `'category'`
  - Una lista: `['int64', 'float64']`
  - Una tupla: `(np.number, np.object)`  

  Ejemplo:  
  `df.select_dtypes(include=['number'])` → selecciona todas las columnas numéricas (int o float).

- exclude: especifica los tipos de datos que quieres excluir.  
  Funciona igual que include, pero elimina esas columnas.  

  Ejemplo:  
  `df.select_dtypes(exclude=['object'])` → selecciona todas las columnas que no sean de texto.
"""

DataFrame numérico:
      Edad  IngresoMensual  GastosMensuales  NumeroComprasMes  \
0    48.0          3283.0           2864.0               7.0
1    32.0          2428.0           1735.0               3.0
2    68.0          2939.0           1056.0              16.0
3    31.0           763.0           2990.0              19.0
4    20.0          1674.0            781.0               5.0
..    ...             ...              ...               ...
195  63.0          3318.0           1157.0               0.0
196  38.0          1863.0            894.0               3.0
197  62.0          2247.0           2566.0              17.0
198  19.0          1222.0           1151.0               3.0
199  60.0          4381.0            983.0               7.0

     PuntuacionFidelidad
0                    2.0
1                   16.3
2                   89.6
3                   15.3
4                   25.9
..                   ...
195                 19.7
196                 60.6
197                 97.5
198                 19.9
199                 43.5

[200 rows x 5 columns]

"\n- include: especifica los tipos de datos que quieres incluir.  \n  Puede ser:\n  - Una cadena: `'number'`, `'object'`, `'float'`, `'int'`, `'bool'`, `'datetime'`, `'category'`\n  - Una lista: `['int64', 'float64']`\n  - Una tupla: `(np.number, np.object)`  \n\n  Ejemplo:  \n  `df.select_dtypes(include=['number'])` → selecciona todas las columnas numéricas (int o float).\n\n- exclude: especifica los tipos de datos que quieres excluir.  \n  Funciona igual que include, pero elimina esas columnas.  \n\n  Ejemplo:  \n  `df.select_dtypes(exclude=['object'])` → selecciona todas las columnas que no sean de texto.\n"

In [45]:
# Personas mayores de 60 con ingreso mayor a 3000
df.query("Edad > 60 and IngresoMensual > 3000")

### Uso de `df.query`
"""
La función **`query()`** de Pandas permite filtrar filas de un DataFrame utilizando expresiones lógicas escritas como cadenas de texto.

#### Parámetros principales
- expr (string): expresión lógica que define la condición de filtrado.  
  - Se escriben las condiciones usando los nombres de las columnas directamente.  
  - Se pueden combinar condiciones con operadores lógicos:
    - `and` → Y lógico  
    - `or` → O lógico  
    - `not` → Negación  
Ejemplo: 
df.query("not IngresoMensual > 3000")
"""

'\nLa función **`query()`** de Pandas permite filtrar filas de un DataFrame utilizando expresiones lógicas escritas como cadenas de texto.\n\n#### Parámetros principales\n- expr (string): expresión lógica que define la condición de filtrado.  \n  - Se escriben las condiciones usando los nombres de las columnas directamente.  \n  - Se pueden combinar condiciones con operadores lógicos:\n    - `and` → Y lógico  \n    - `or` → O lógico  \n    - `not` → Negación  \nEjemplo: \ndf.query("not IngresoMensual > 3000")\n'

In [46]:
# Mostrar IngresoMensual solo si es mayor a 2000
df["IngresoMensual"].where(df["IngresoMensual"] > 2000)

0      3283.0
1      2428.0
2      2939.0
3         NaN
4         NaN
        ...
195    3318.0
196       NaN
197    2247.0
198       NaN
199    4381.0
Name: IngresoMensual, Length: 200, dtype: float64

In [47]:
# Ocultar IngresoMensual si es menor o igual a 2000
df["IngresoMensual"].mask(df["IngresoMensual"] <= 2000)

0      3283.0
1      2428.0
2      2939.0
3         NaN
4         NaN
        ...
195    3318.0
196       NaN
197    2247.0
198       NaN
199    4381.0
Name: IngresoMensual, Length: 200, dtype: float64

In [48]:
# Clientes VIP y canal presencial
# SIEMPRE usar paréntesis: df[(condicion1) & (condicion2)]

df[(df["TipoCliente"] == "VIP") & (df["CanalPreferido"] == "Presencial")]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
6,7,67.0,1390.0,414.0,M,Casado/a,Oruro,True,False,Secundaria,6.0,31.2,VIP,Presencial,A,False
13,14,44.0,3349.0,580.0,F,Viudo/a,Sucre,False,True,Universitaria,13.0,43.8,VIP,Presencial,D,True
14,15,22.0,1903.0,2613.0,F,Casado/a,Oruro,False,False,Universitaria,6.0,5.0,VIP,Presencial,D,False
27,28,53.0,2320.0,2268.0,F,Soltero/a,Cochabamba,True,False,Postgrado,19.0,19.9,VIP,Presencial,C,True
34,35,32.0,2824.0,1796.0,M,Soltero/a,Cochabamba,False,True,Postgrado,9.0,85.7,VIP,Presencial,A,False
43,44,44.0,1239.0,2292.0,M,Viudo/a,Cochabamba,True,True,Primaria,13.0,91.9,VIP,Presencial,C,True
46,47,70.0,4873.0,1919.0,F,Divorciado/a,Cochabamba,False,False,Primaria,4.0,0.5,VIP,Presencial,D,False
47,48,44.0,2599.0,101.0,F,Casado/a,Cochabamba,True,True,Primaria,8.0,37.0,VIP,Presencial,C,False
60,61,42.0,1840.0,2917.0,F,Divorciado/a,Sucre,True,False,Universitaria,15.0,23.1,VIP,Presencial,A,True
69,70,69.0,4095.0,2382.0,F,Viudo/a,Sucre,False,False,Primaria,7.0,77.7,VIP,Presencial,D,False
79,80,34.0,2715.0,1090.0,F,Casado/a,La Paz,False,False,Primaria,4.0,16.9,VIP,Presencial,C,False
87,88,42.0,1570.0,2334.0,F,Divorciado/a,Sucre,False,True,Primaria,13.0,28.2,VIP,Presencial,C,True
92,93,63.0,1162.0,1005.0,F,Divorciado/a,Santa Cruz,False,True,Universitaria,1.0,23.8,VIP,Presencial,B,False
102,103,47.0,3820.0,1396.0,M,Viudo/a,Sucre,True,False,Primaria,19.0,66.4,VIP,Presencial,A,True
108,109,20.0,3398.0,1653.0,F,Casado/a,Sucre,True,False,Postgrado,3.0,47.1,VIP,Presencial,C,False
123,124,37.0,1234.0,2675.0,M,Casado/a,Santa Cruz,True,False,Universitaria,13.0,19.4,VIP,Presencial,C,True
129,130,63.0,4259.0,147.0,M,Soltero/a,Sucre,True,True,Universitaria,7.0,92.7,VIP,Presencial,A,False
140,141,40.0,2398.0,1705.0,M,Viudo/a,Sucre,True,True,Primaria,10.0,31.2,VIP,Presencial,C,True
142,143,55.0,4399.0,1804.0,F,Casado/a,Santa Cruz,True,False,Postgrado,18.0,65.8,VIP,Presencial,D,True
143,144,63.0,2548.0,1328.0,M,Viudo/a,Oruro,True,False,Primaria,20.0,73.6,VIP,Presencial,D,True
149,150,23.0,4871.0,1521.0,F,Divorciado/a,La Paz,True,True,Primaria,11.0,86.6,VIP,Presencial,B,True
174,175,47.0,2280.0,605.0,M,Casado/a,Santa Cruz,True,False,Postgrado,5.0,79.8,VIP,Presencial,C,False
181,182,65.0,4242.0,380.0,M,Viudo/a,Oruro,True,False,Secundaria,19.0,26.2,VIP,Presencial,A,True
194,195,25.0,4510.0,222.0,M,Casado/a,Santa Cruz,True,True,Primaria,18.0,45.1,VIP,Presencial,C,True
197,198,62.0,2247.0,2566.0,M,Divorciado/a,Cochabamba,False,False,Secundaria,17.0,97.5,VIP,Presencial,C,True
199,200,60.0,4381.0,983.0,M,Soltero/a,Oruro,False,True,Secundaria,7.0,43.5,VIP,Presencial,D,False

In [49]:
# Personas jóvenes o con ingreso alto (OR)
df[(df["Edad"] < 25) | (df["IngresoMensual"] > 4000)]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
4,5,20.0,1674.0,781.0,M,Soltero/a,Cochabamba,False,True,Primaria,5.0,25.9,VIP,Online,B,False
7,8,60.0,4244.0,1512.0,F,Viudo/a,La Paz,False,True,Primaria,10.0,22.1,Regular,Online,A,True
9,10,69.0,4115.0,567.0,F,Soltero/a,Cochabamba,True,False,Secundaria,0.0,90.3,VIP,Online,B,False
14,15,22.0,1903.0,2613.0,F,Casado/a,Oruro,False,False,Universitaria,6.0,5.0,VIP,Presencial,D,False
17,18,45.0,4862.0,527.0,F,Casado/a,Sucre,True,True,Secundaria,14.0,37.1,Premium,Teléfono,A,True
18,19,26.0,4853.0,1138.0,M,Casado/a,Cochabamba,False,True,Postgrado,13.0,50.3,Premium,Teléfono,D,True
23,24,24.0,1704.0,269.0,M,Divorciado/a,Oruro,False,True,Secundaria,1.0,61.4,VIP,Online,C,False
25,26,26.0,4034.0,2681.0,F,Soltero/a,Santa Cruz,False,True,Primaria,12.0,22.8,Regular,Online,C,True
29,30,34.0,4406.0,462.0,F,Divorciado/a,Santa Cruz,False,False,Secundaria,15.0,88.4,Premium,Presencial,A,True
30,31,60.0,4666.0,2927.0,M,Soltero/a,Oruro,False,False,Universitaria,20.0,23.8,Premium,Teléfono,C,True
31,32,56.0,4469.0,1365.0,M,Soltero/a,Santa Cruz,True,True,Primaria,0.0,29.2,Premium,Teléfono,B,False
33,34,29.0,4776.0,579.0,M,Viudo/a,La Paz,True,True,Primaria,17.0,61.9,VIP,Teléfono,C,True
38,39,24.0,590.0,920.0,F,Viudo/a,Oruro,False,True,Postgrado,1.0,62.1,VIP,Online,D,False
40,41,58.0,4420.0,372.0,F,Casado/a,Sucre,False,False,Universitaria,16.0,19.0,Premium,Presencial,A,True
45,46,24.0,3808.0,1389.0,F,Divorciado/a,Cochabamba,True,True,Secundaria,7.0,54.7,Premium,Teléfono,D,False
46,47,70.0,4873.0,1919.0,F,Divorciado/a,Cochabamba,False,False,Primaria,4.0,0.5,VIP,Presencial,D,False
53,54,22.0,1512.0,2094.0,F,Divorciado/a,Santa Cruz,False,False,Postgrado,10.0,20.2,VIP,Online,A,True
63,64,32.0,4462.0,2135.0,F,Soltero/a,Sucre,False,True,Primaria,5.0,25.8,Regular,Teléfono,A,False
65,66,64.0,4175.0,2980.0,F,Soltero/a,Sucre,True,True,Universitaria,20.0,2.2,Regular,Online,D,True
66,67,43.0,4920.0,834.0,F,Viudo/a,Oruro,False,False,Secundaria,4.0,21.1,Premium,Online,D,False
69,70,69.0,4095.0,2382.0,F,Viudo/a,Sucre,False,False,Primaria,7.0,77.7,VIP,Presencial,D,False
70,71,47.0,4031.0,1125.0,F,Viudo/a,Oruro,True,False,Postgrado,9.0,7.3,VIP,Teléfono,A,False
71,72,23.0,542.0,1163.0,M,Viudo/a,La Paz,False,True,Postgrado,13.0,9.9,Premium,Teléfono,D,True
72,73,60.0,4006.0,933.0,M,Soltero/a,La Paz,False,True,Universitaria,14.0,94.6,Premium,Online,C,True
83,84,21.0,749.0,1247.0,F,Soltero/a,Sucre,True,True,Primaria,1.0,46.0,Premium,Online,C,False
85,86,22.0,4113.0,598.0,F,Viudo/a,Oruro,False,False,Secundaria,4.0,77.9,Premium,Online,C,False
86,87,68.0,4261.0,1419.0,F,Soltero/a,Cochabamba,True,False,Primaria,16.0,82.4,VIP,Online,B,True
89,90,39.0,4356.0,2464.0,M,Divorciado/a,Cochabamba,True,False,Secundaria,9.0,49.6,Regular,Teléfono,A,False
90,91,42.0,4342.0,973.0,F,Divorciado/a,La Paz,True,False,Postgrado,12.0,6.6,Regular,Online,D,True
96,97,57.0,4997.0,2719.0,M,Viudo/a,Sucre,True,False,Secundaria,17.0,71.4,Regular,Presencial,A,True
99,100,29.0,4618.0,978.0,F,Casado/a,Santa Cruz,True,False,Postgrado,14.0,48.3,Regular,Presencial,C,True
103,104,52.0,4253.0,2468.0,M,Viudo/a,La Paz,False,True,Secundaria,1.0,72.8,VIP,Online,C,False
107,108,24.0,3387.0,2505.0,M,Divorciado/a,Oruro,False,False,Universitaria,6.0,20.5,Regular,Online,C,False
108,109,20.0,3398.0,1653.0,F,Casado/a,Sucre,True,False,Postgrado,3.0,47.1,VIP,Presencial,C,False
109,110,40.0,4900.0,896.0,M,Soltero/a,Oruro,True,True,Postgrado,4.0,37.9,Premium,Online,C,False
116,117,67.0,4925.0,336.0,M,Casado/a,Santa Cruz,True,True,Primaria,11.0,0.8,Premium,Presencial,C,True
121,122,39.0,4854.0,694.0,F,Viudo/a,Sucre,False,True,Postgrado,14.0,56.2,VIP,Online,C,True
125,126,34.0,4937.0,1802.0,F,Casado/a,La Paz,True,False,Primaria,15.0,56.6,Regular,Teléfono,C,True
129,130,63.0,4259.0,147.0,M,Soltero/a,Sucre,True,True,Universitaria,7.0,92.7,VIP,Presencial,A,False
132,133,32.0,4535.0,2331.0,F,Divorciado/a,Cochabamba,False,True,Postgrado,14.0,54.5,Regular,Online,B,True
135,136,40.0,4028.0,1996.0,F,Viudo/a,Santa Cruz,False,True,Postgrado,18.0,73.2,Regular,Online,A,True
137,138,24.0,580.0,2456.0,F,Soltero/a,Santa Cruz,False,True,Primaria,5.0,22.4,Regular,Online,A,False
142,143,55.0,4399.0,1804.0,F,Casado/a,Santa Cruz,True,False,Postgrado,18.0,65.8,VIP,Presencial,D,True
145,146,24.0,4837.0,2156.0,F,Divorciado/a,Oruro,False,True,Primaria,20.0,86.4,Premium,Teléfono,D,True
148,149,22.0,1890.0,1744.0,F,Viudo/a,Oruro,True,True,Primaria,18.0,1.2,Regular,Teléfono,D,True
149,150,23.0,4871.0,1521.0,F,Divorciado/a,La Paz,True,True,Primaria,11.0,86.6,VIP,Presencial,B,True
155,156,53.0,4613.0,539.0,M,Soltero/a,Cochabamba,False,False,Primaria,11.0,58.0,Premium,Teléfono,D,True
160,161,56.0,4897.0,1627.0,M,Soltero/a,Cochabamba,True,True,Secundaria,6.0,49.6,Premium,Presencial,B,False
163,164,24.0,4036.0,449.0,F,Casado/a,Cochabamba,False,True,Postgrado,15.0,44.6,VIP,Teléfono,A,True
169,170,64.0,4961.0,193.0,F,Viudo/a,Santa Cruz,True,False,Primaria,12.0,6.8,Premium,Presencial,A,True
170,171,56.0,4937.0,788.0,M,Soltero/a,Cochabamba,False,False,Secundaria,5.0,53.2,Regular,Teléfono,C,False
171,172,21.0,1117.0,2091.0,M,Viudo/a,Sucre,False,False,Universitaria,9.0,12.3,Regular,Online,A,False
172,173,18.0,4574.0,755.0,F,Casado/a,Sucre,False,False,Universitaria,7.0,67.6,Premium,Teléfono,B,False
181,182,65.0,4242.0,380.0,M,Viudo/a,Oruro,True,False,Secundaria,19.0,26.2,VIP,Presencial,A,True
184,185,20.0,1742.0,1793.0,F,Casado/a,Cochabamba,True,False,Secundaria,5.0,58.0,Regular,Online,D,False
186,187,53.0,4778.0,2686.0,F,Divorciado/a,Cochabamba,False,True,Primaria,17.0,34.0,VIP,Online,B,True
194,195,25.0,4510.0,222.0,M,Casado/a,Santa Cruz,True,True,Primaria,18.0,45.1,VIP,Presencial,C,True
198,199,19.0,1222.0,1151.0,F,Soltero/a,La Paz,False,False,Secundaria,3.0,19.9,Regular,Presencial,D,False
199,200,60.0,4381.0,983.0,M,Soltero/a,Oruro,False,True,Secundaria,7.0,43.5,VIP,Presencial,D,False

In [50]:
# Clientes que NO tienen tarjeta de crédito
# ~ (operador de negación lógica): Invierte los valores booleanos: True pasa a False y False pasa a True
df[~df["TieneTarjetaCredito"]]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
3,4,31.0,763.0,2990.0,F,Soltero/a,Santa Cruz,False,True,Secundaria,19.0,15.3,VIP,Online,C,True
4,5,20.0,1674.0,781.0,M,Soltero/a,Cochabamba,False,True,Primaria,5.0,25.9,VIP,Online,B,False
7,8,60.0,4244.0,1512.0,F,Viudo/a,La Paz,False,True,Primaria,10.0,22.1,Regular,Online,A,True
13,14,44.0,3349.0,580.0,F,Viudo/a,Sucre,False,True,Universitaria,13.0,43.8,VIP,Presencial,D,True
14,15,22.0,1903.0,2613.0,F,Casado/a,Oruro,False,False,Universitaria,6.0,5.0,VIP,Presencial,D,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,194,28.0,1949.0,1193.0,M,Divorciado/a,Santa Cruz,False,False,Universitaria,7.0,64.1,Regular,Teléfono,B,False
196,197,38.0,1863.0,894.0,F,Casado/a,Oruro,False,False,Primaria,3.0,60.6,Regular,Teléfono,B,False
197,198,62.0,2247.0,2566.0,M,Divorciado/a,Cochabamba,False,False,Secundaria,17.0,97.5,VIP,Presencial,C,True
198,199,19.0,1222.0,1151.0,F,Soltero/a,La Paz,False,False,Secundaria,3.0,19.9,Regular,Presencial,D,False
199,200,60.0,4381.0,983.0,M,Soltero/a,Oruro,False,True,Secundaria,7.0,43.5,VIP,Presencial,D,False

In [51]:
# Clientes de La Paz u Oruro
df[df["Ciudad"].isin(["La Paz", "Oruro"])]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
6,7,67.0,1390.0,414.0,M,Casado/a,Oruro,True,False,Secundaria,6.0,31.2,VIP,Presencial,A,False
7,8,60.0,4244.0,1512.0,F,Viudo/a,La Paz,False,True,Primaria,10.0,22.1,Regular,Online,A,True
14,15,22.0,1903.0,2613.0,F,Casado/a,Oruro,False,False,Universitaria,6.0,5.0,VIP,Presencial,D,False
15,16,68.0,3760.0,2155.0,M,Viudo/a,Oruro,True,True,Postgrado,2.0,36.0,Premium,Online,B,False
19,20,46.0,3770.0,2053.0,F,Divorciado/a,Oruro,False,False,Universitaria,11.0,52.8,Premium,Online,B,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,191,66.0,2964.0,2720.0,M,Divorciado/a,La Paz,False,False,Secundaria,4.0,98.8,VIP,Teléfono,C,False
192,193,37.0,3183.0,2349.0,F,Viudo/a,La Paz,False,True,Secundaria,12.0,25.4,VIP,Online,A,True
196,197,38.0,1863.0,894.0,F,Casado/a,Oruro,False,False,Primaria,3.0,60.6,Regular,Teléfono,B,False
198,199,19.0,1222.0,1151.0,F,Soltero/a,La Paz,False,False,Secundaria,3.0,19.9,Regular,Presencial,D,False
199,200,60.0,4381.0,983.0,M,Soltero/a,Oruro,False,True,Secundaria,7.0,43.5,VIP,Presencial,D,False

In [52]:
# Ingresos mensuales entre 2000 y 3500
df[df["IngresoMensual"].between(2000, 3500)]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
0,1,48.0,3283.0,2864.0,M,Casado/a,Cochabamba,True,True,Postgrado,7.0,2.0,Regular,Teléfono,C,False
1,2,32.0,2428.0,1735.0,F,Viudo/a,Cochabamba,True,True,Universitaria,3.0,16.3,Regular,Online,D,False
2,3,68.0,2939.0,1056.0,M,Casado/a,Sucre,True,True,Universitaria,16.0,89.6,Premium,Online,B,True
5,6,59.0,2287.0,1877.0,M,Viudo/a,Cochabamba,True,False,Universitaria,6.0,24.4,VIP,Teléfono,A,False
10,11,31.0,2961.0,921.0,F,Casado/a,Cochabamba,True,True,Universitaria,18.0,95.9,Regular,Teléfono,C,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,191,66.0,2964.0,2720.0,M,Divorciado/a,La Paz,False,False,Secundaria,4.0,98.8,VIP,Teléfono,C,False
191,192,59.0,3399.0,2610.0,F,Soltero/a,Santa Cruz,False,False,Secundaria,4.0,65.5,VIP,Online,D,False
192,193,37.0,3183.0,2349.0,F,Viudo/a,La Paz,False,True,Secundaria,12.0,25.4,VIP,Online,A,True
195,196,63.0,3318.0,1157.0,F,Casado/a,Santa Cruz,True,True,Universitaria,0.0,19.7,Premium,Online,D,False
197,198,62.0,2247.0,2566.0,M,Divorciado/a,Cochabamba,False,False,Secundaria,17.0,97.5,VIP,Presencial,C,True

In [53]:
# Clientes solteros menores de 30 años
df[(df["EstadoCivil"] == "Soltero/a") & (df["Edad"] < 30)]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
4,5,20.0,1674.0,781.0,M,Soltero/a,Cochabamba,False,True,Primaria,5.0,25.9,VIP,Online,B,False
25,26,26.0,4034.0,2681.0,F,Soltero/a,Santa Cruz,False,True,Primaria,12.0,22.8,Regular,Online,C,True
73,74,25.0,3782.0,332.0,M,Soltero/a,La Paz,False,False,Postgrado,18.0,93.1,Premium,Online,C,True
83,84,21.0,749.0,1247.0,F,Soltero/a,Sucre,True,True,Primaria,1.0,46.0,Premium,Online,C,False
113,114,25.0,1513.0,903.0,M,Soltero/a,Oruro,False,True,Secundaria,0.0,1.4,Premium,Teléfono,B,False
115,116,27.0,2166.0,2896.0,M,Soltero/a,Oruro,True,False,Universitaria,20.0,37.5,Premium,Online,A,True
137,138,24.0,580.0,2456.0,F,Soltero/a,Santa Cruz,False,True,Primaria,5.0,22.4,Regular,Online,A,False
162,163,26.0,3767.0,2910.0,M,Soltero/a,Oruro,False,False,Primaria,6.0,84.6,VIP,Teléfono,D,False
180,181,28.0,1926.0,1926.0,M,Soltero/a,Santa Cruz,False,True,Primaria,18.0,83.3,VIP,Teléfono,B,True
198,199,19.0,1222.0,1151.0,F,Soltero/a,La Paz,False,False,Secundaria,3.0,19.9,Regular,Presencial,D,False

In [54]:
# Filas con valores faltantes
df[df["IngresoMensual"].isna()]

# Filas sin valores faltantes en IngresoMensual
df[df["IngresoMensual"].notna()]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
0,1,48.0,3283.0,2864.0,M,Casado/a,Cochabamba,True,True,Postgrado,7.0,2.0,Regular,Teléfono,C,False
1,2,32.0,2428.0,1735.0,F,Viudo/a,Cochabamba,True,True,Universitaria,3.0,16.3,Regular,Online,D,False
2,3,68.0,2939.0,1056.0,M,Casado/a,Sucre,True,True,Universitaria,16.0,89.6,Premium,Online,B,True
3,4,31.0,763.0,2990.0,F,Soltero/a,Santa Cruz,False,True,Secundaria,19.0,15.3,VIP,Online,C,True
4,5,20.0,1674.0,781.0,M,Soltero/a,Cochabamba,False,True,Primaria,5.0,25.9,VIP,Online,B,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,63.0,3318.0,1157.0,F,Casado/a,Santa Cruz,True,True,Universitaria,0.0,19.7,Premium,Online,D,False
196,197,38.0,1863.0,894.0,F,Casado/a,Oruro,False,False,Primaria,3.0,60.6,Regular,Teléfono,B,False
197,198,62.0,2247.0,2566.0,M,Divorciado/a,Cochabamba,False,False,Secundaria,17.0,97.5,VIP,Presencial,C,True
198,199,19.0,1222.0,1151.0,F,Soltero/a,La Paz,False,False,Secundaria,3.0,19.9,Regular,Presencial,D,False
199,200,60.0,4381.0,983.0,M,Soltero/a,Oruro,False,True,Secundaria,7.0,43.5,VIP,Presencial,D,False

In [55]:
# Personas que gastan más de lo que ingresan
df[df["GastosMensuales"] > df["IngresoMensual"]]

,ID,Edad,IngresoMensual,GastosMensuales,Genero,EstadoCivil,Ciudad,TieneTarjetaCredito,TieneCuentaAhorro,NivelEducacion,NumeroComprasMes,PuntuacionFidelidad,TipoCliente,CanalPreferido,ProductoFavorito,ClienteActivo
3,4,31.0,763.0,2990.0,F,Soltero/a,Santa Cruz,False,True,Secundaria,19.0,15.3,VIP,Online,C,True
12,13,43.0,1273.0,2222.0,M,Viudo/a,Sucre,True,False,Postgrado,16.0,45.3,Regular,Online,C,True
14,15,22.0,1903.0,2613.0,F,Casado/a,Oruro,False,False,Universitaria,6.0,5.0,VIP,Presencial,D,False
16,17,44.0,2295.0,2305.0,M,Divorciado/a,Sucre,True,False,Postgrado,0.0,89.7,VIP,Teléfono,B,False
26,27,36.0,1256.0,2454.0,F,Divorciado/a,Cochabamba,True,False,Postgrado,18.0,90.2,Regular,Teléfono,C,True
37,38,62.0,2063.0,2105.0,M,Viudo/a,Oruro,False,True,Universitaria,0.0,16.9,Premium,Teléfono,D,False
38,39,24.0,590.0,920.0,F,Viudo/a,Oruro,False,True,Postgrado,1.0,62.1,VIP,Online,D,False
41,42,27.0,528.0,2484.0,M,Casado/a,Santa Cruz,False,True,Secundaria,13.0,56.9,VIP,Online,A,True
42,43,40.0,824.0,1340.0,M,Casado/a,Santa Cruz,True,True,Primaria,17.0,67.2,Regular,Online,D,True
43,44,44.0,1239.0,2292.0,M,Viudo/a,Cochabamba,True,True,Primaria,13.0,91.9,VIP,Presencial,C,True
51,52,51.0,1117.0,2460.0,M,Divorciado/a,La Paz,True,False,Primaria,6.0,11.8,VIP,Teléfono,C,False
53,54,22.0,1512.0,2094.0,F,Divorciado/a,Santa Cruz,False,False,Postgrado,10.0,20.2,VIP,Online,A,True
54,55,25.0,761.0,2805.0,M,Divorciado/a,La Paz,True,True,Secundaria,17.0,58.7,VIP,Online,A,True
57,58,35.0,1516.0,2067.0,M,Viudo/a,Sucre,True,True,Secundaria,2.0,37.0,Regular,Online,A,False
58,59,50.0,746.0,1344.0,F,Casado/a,Sucre,True,False,Primaria,13.0,69.8,Regular,Online,C,True
60,61,42.0,1840.0,2917.0,F,Divorciado/a,Sucre,True,False,Universitaria,15.0,23.1,VIP,Presencial,A,True
62,63,38.0,824.0,1433.0,M,Viudo/a,Santa Cruz,True,False,Universitaria,5.0,7.9,Premium,Online,A,False
68,69,33.0,946.0,2090.0,F,Divorciado/a,Oruro,False,True,Postgrado,9.0,71.7,Premium,Online,B,False
71,72,23.0,542.0,1163.0,M,Viudo/a,La Paz,False,True,Postgrado,13.0,9.9,Premium,Teléfono,D,True
76,77,56.0,1205.0,1655.0,M,Viudo/a,Sucre,False,False,Universitaria,14.0,15.6,VIP,Online,C,True
77,78,48.0,537.0,1561.0,M,Divorciado/a,La Paz,False,False,Universitaria,9.0,91.0,Regular,Teléfono,D,False
78,79,65.0,2536.0,2841.0,F,Divorciado/a,Cochabamba,True,True,Primaria,4.0,92.2,Premium,Presencial,D,False
83,84,21.0,749.0,1247.0,F,Soltero/a,Sucre,True,True,Primaria,1.0,46.0,Premium,Online,C,False
84,85,30.0,2097.0,2234.0,M,Viudo/a,Santa Cruz,True,True,Primaria,10.0,46.5,VIP,Online,D,True
87,88,42.0,1570.0,2334.0,F,Divorciado/a,Sucre,False,True,Primaria,13.0,28.2,VIP,Presencial,C,True
94,95,40.0,967.0,1605.0,F,Soltero/a,Oruro,True,True,Secundaria,8.0,42.2,Regular,Online,A,False
95,96,52.0,652.0,2069.0,M,Divorciado/a,La Paz,True,False,Universitaria,18.0,55.0,VIP,Teléfono,A,True
98,99,47.0,2023.0,2968.0,M,Divorciado/a,Santa Cruz,False,True,Universitaria,13.0,89.6,VIP,Teléfono,D,True
101,102,63.0,1788.0,2094.0,M,Viudo/a,Oruro,True,False,Secundaria,7.0,32.0,VIP,Teléfono,A,False
110,111,32.0,2366.0,2423.0,M,Viudo/a,La Paz,True,False,Primaria,10.0,24.8,Regular,Presencial,A,True
115,116,27.0,2166.0,2896.0,M,Soltero/a,Oruro,True,False,Universitaria,20.0,37.5,Premium,Online,A,True
117,118,59.0,2247.0,2578.0,F,Casado/a,Sucre,False,True,Universitaria,6.0,98.1,Premium,Online,C,False
118,119,61.0,1532.0,2426.0,M,Divorciado/a,Oruro,True,True,Postgrado,4.0,37.8,Regular,Presencial,C,False
123,124,37.0,1234.0,2675.0,M,Casado/a,Santa Cruz,True,False,Universitaria,13.0,19.4,VIP,Presencial,C,True
131,132,47.0,1368.0,2795.0,M,Soltero/a,La Paz,False,True,Postgrado,12.0,21.0,Regular,Online,A,True
137,138,24.0,580.0,2456.0,F,Soltero/a,Santa Cruz,False,True,Primaria,5.0,22.4,Regular,Online,A,False
141,142,43.0,2043.0,2728.0,M,Soltero/a,La Paz,False,False,Primaria,13.0,22.7,Regular,Online,C,True
152,153,49.0,2177.0,2577.0,M,Viudo/a,Cochabamba,False,True,Primaria,3.0,43.4,VIP,Teléfono,B,False
157,158,63.0,1770.0,2033.0,F,Viudo/a,Oruro,False,False,Universitaria,4.0,33.5,VIP,Teléfono,C,False
158,159,36.0,927.0,2934.0,F,Casado/a,Cochabamba,False,True,Universitaria,18.0,38.2,Regular,Presencial,A,True
159,160,42.0,1447.0,1790.0,F,Casado/a,Cochabamba,False,False,Secundaria,12.0,60.6,VIP,Online,D,True
165,166,65.0,1578.0,2654.0,M,Divorciado/a,La Paz,True,True,Primaria,10.0,79.6,Regular,Online,C,True
167,168,36.0,955.0,1079.0,F,Casado/a,Santa Cruz,True,True,Primaria,5.0,1.5,Regular,Online,A,False
168,169,69.0,1031.0,2694.0,F,Viudo/a,Santa Cruz,True,True,Postgrado,11.0,74.3,Premium,Teléfono,A,True
171,172,21.0,1117.0,2091.0,M,Viudo/a,Sucre,False,False,Universitaria,9.0,12.3,Regular,Online,A,False
177,178,42.0,871.0,2486.0,M,Viudo/a,La Paz,True,True,Primaria,20.0,16.0,Regular,Teléfono,C,True
183,184,57.0,2741.0,2980.0,M,Divorciado/a,Oruro,True,True,Universitaria,0.0,34.8,VIP,Teléfono,B,False
184,185,20.0,1742.0,1793.0,F,Casado/a,Cochabamba,True,False,Secundaria,5.0,58.0,Regular,Online,D,False
185,186,46.0,1364.0,2367.0,M,Soltero/a,Sucre,False,False,Universitaria,4.0,80.4,VIP,Teléfono,C,False
187,188,69.0,1948.0,2289.0,M,Divorciado/a,Cochabamba,False,True,Postgrado,6.0,13.5,Premium,Teléfono,A,False
188,189,61.0,2653.0,2940.0,F,Viudo/a,Sucre,True,False,Primaria,16.0,77.4,Premium,Presencial,C,True
197,198,62.0,2247.0,2566.0,M,Divorciado/a,Cochabamba,False,False,Secundaria,17.0,97.5,VIP,Presencial,C,True

In [56]:
# Solo Edad, Ingreso y Ciudad para clientes Premium
df.loc[df["TipoCliente"] == "Premium", ["Edad", "IngresoMensual", "Ciudad"]]

     Edad  IngresoMensual      Ciudad
2    68.0          2939.0       Sucre
15   68.0          3760.0       Oruro
17   45.0          4862.0       Sucre
18   26.0          4853.0  Cochabamba
19   46.0          3770.0       Oruro
..    ...             ...         ...
178  33.0          2027.0      La Paz
187  69.0          1948.0  Cochabamba
188  61.0          2653.0       Sucre
189  39.0           626.0       Sucre
195  63.0          3318.0  Santa Cruz

[63 rows x 3 columns]

## 4. Operaciones básicas

In [57]:
# Ordenar por edad
print("\nOrdenar por Edad:\n", df.head(15).sort_values("Edad"))

Ordenar por Edad:
     ID  Edad  IngresoMensual  GastosMensuales Genero   EstadoCivil  \
4    5  20.0          1674.0            781.0      M     Soltero/a
14  15  22.0          1903.0           2613.0      F      Casado/a
10  11  31.0          2961.0            921.0      F      Casado/a
3    4  31.0           763.0           2990.0      F     Soltero/a
1    2  32.0          2428.0           1735.0      F       Viudo/a
11  12  42.0          3480.0           1793.0      F     Soltero/a
12  13  43.0          1273.0           2222.0      M       Viudo/a
13  14  44.0          3349.0            580.0      F       Viudo/a
0    1  48.0          3283.0           2864.0      M      Casado/a
8    9  54.0          1188.0            388.0      F  Divorciado/a
5    6  59.0          2287.0           1877.0      M       Viudo/a
7    8  60.0          4244.0           1512.0      F       Viudo/a
6    7  67.0          1390.0            414.0      M      Casado/a
2    3  68.0          2939.0           1056.0      M      Casado/a
9   10  69.0          4115.0            567.0      F     Soltero/a

        Ciudad  TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  \
4   Cochabamba                False               True       Primaria
14       Oruro                False              False  Universitaria
10  Cochabamba                 True               True  Universitaria
3   Santa Cruz                False               True     Secundaria
1   Cochabamba                 True               True  Universitaria
11       Sucre                 True              False  Universitaria
12       Sucre                 True              False      Postgrado
13       Sucre                False               True  Universitaria
0   Cochabamba                 True               True      Postgrado
8   Santa Cruz                 True              False  Universitaria
5   Cochabamba                 True              False  Universitaria
7       La Paz                False               True       Primaria
6        Oruro                 True              False     Secundaria
2        Sucre                 True               True  Universitaria
9   Cochabamba                 True              False     Secundaria

    NumeroComprasMes  PuntuacionFidelidad TipoCliente CanalPreferido  \
4                5.0                 25.9         VIP         Online
14               6.0                  5.0         VIP     Presencial
10              18.0                 95.9     Regular       Teléfono
3               19.0                 15.3         VIP         Online
1                3.0                 16.3     Regular         Online
11               7.0                 94.3     Regular         Online
12              16.0                 45.3     Regular         Online
13              13.0                 43.8         VIP     Presencial
0                7.0                  2.0     Regular       Teléfono
8               20.0                  3.1     Regular     Presencial
5                6.0                 24.4         VIP       Teléfono
7               10.0                 22.1     Regular         Online
6                6.0                 31.2         VIP     Presencial
2               16.0                 89.6     Premium         Online
9                0.0                 90.3         VIP         Online

   ProductoFavorito ClienteActivo
4                 B         False
14                D         False
10                C          True
3                 C          True
1                 D         False
11                C         False
12                C          True
13                D          True
0                 C         False
8                 D          True
5                 A         False
7                 A          True
6                 A         False
2                 B          True
9                 B         False

In [58]:
# Ordenar por índice
print("\nOrdenar por índice:\n", df.head(8).sort_index())

Ordenar por índice:
   ID  Edad  IngresoMensual  GastosMensuales Genero EstadoCivil      Ciudad  \
0  1  48.0          3283.0           2864.0      M    Casado/a  Cochabamba
1  2  32.0          2428.0           1735.0      F     Viudo/a  Cochabamba
2  3  68.0          2939.0           1056.0      M    Casado/a       Sucre
3  4  31.0           763.0           2990.0      F   Soltero/a  Santa Cruz
4  5  20.0          1674.0            781.0      M   Soltero/a  Cochabamba
5  6  59.0          2287.0           1877.0      M     Viudo/a  Cochabamba
6  7  67.0          1390.0            414.0      M    Casado/a       Oruro
7  8  60.0          4244.0           1512.0      F     Viudo/a      La Paz

   TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  NumeroComprasMes  \
0                 True               True      Postgrado               7.0
1                 True               True  Universitaria               3.0
2                 True               True  Universitaria              16.0
3                False               True     Secundaria              19.0
4                False               True       Primaria               5.0
5                 True              False  Universitaria               6.0
6                 True              False     Secundaria               6.0
7                False               True       Primaria              10.0

   PuntuacionFidelidad TipoCliente CanalPreferido ProductoFavorito  \
0                  2.0     Regular       Teléfono                C
1                 16.3     Regular         Online                D
2                 89.6     Premium         Online                B
3                 15.3         VIP         Online                C
4                 25.9         VIP         Online                B
5                 24.4         VIP       Teléfono                A
6                 31.2         VIP     Presencial                A
7                 22.1     Regular         Online                A

  ClienteActivo
0         False
1         False
2          True
3          True
4         False
5         False
6         False
7          True

In [59]:
# Agregar columna
print("\nAgregar columna:\n")
df["MayorDe30"] = df["Edad"] > 30
print(df.head())

Agregar columna:

  ID  Edad  IngresoMensual  GastosMensuales Genero EstadoCivil      Ciudad  \
0  1  48.0          3283.0           2864.0      M    Casado/a  Cochabamba
1  2  32.0          2428.0           1735.0      F     Viudo/a  Cochabamba
2  3  68.0          2939.0           1056.0      M    Casado/a       Sucre
3  4  31.0           763.0           2990.0      F   Soltero/a  Santa Cruz
4  5  20.0          1674.0            781.0      M   Soltero/a  Cochabamba

   TieneTarjetaCredito  TieneCuentaAhorro NivelEducacion  NumeroComprasMes  \
0                 True               True      Postgrado               7.0
1                 True               True  Universitaria               3.0
2                 True               True  Universitaria              16.0
3                False               True     Secundaria              19.0
4                False               True       Primaria               5.0

   PuntuacionFidelidad TipoCliente CanalPreferido ProductoFavorito  \
0                  2.0     Regular       Teléfono                C
1                 16.3     Regular         Online                D
2                 89.6     Premium         Online                B
3                 15.3         VIP         Online                C
4                 25.9         VIP         Online                B

  ClienteActivo  MayorDe30
0         False       True
1         False       True
2          True       True
3          True       True
4         False      False

## 5. Agrupación y agregación

In [60]:
# Agrupación por Ciudad
print("\nAgrupación por Ciudad:\n", df.groupby("Ciudad")["Edad"].mean())

### Agrupación con `groupby`
"""
La función `groupby()` en Pandas permite agrupar filas de un DataFrame según los valores de una o más columnas, y luego aplicar operaciones de agregación sobre cada grupo.

#### Parámetros principales
- by (string o lista): columna(s) por las que se quiere agrupar.  
- aggfunc (función de agregación): operación que se aplica a cada grupo (ejemplo: `mean`, `sum`, `count`, etc.).

### Operaciones comunes con `groupby`

Después de agrupar con `df.groupby()`, se pueden aplicar distintas funciones de agregación:

- mean() → promedio de cada grupo  
- sum() → suma de valores  
- count() → número de elementos en cada grupo  
- min() / max() → mínimo y máximo de cada grupo  
- median() → mediana de cada grupo  
- std() / var() → desviación estándar y varianza  
- first() / last() → primer o último valor de cada grupo  
- agg() → aplicar múltiples funciones a la vez  
    Ejemplo: df.groupby("Ciudad")["Edad"].agg(["mean", "max", "min"])
"""

Agrupación por Ciudad:
 Ciudad
Cochabamba    46.266667
La Paz        42.944444
Oruro         45.307692
Santa Cruz    44.692308
Sucre         45.853659
Name: Edad, dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_19420\57602015.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("\nAgrupación por Ciudad:\n", df.groupby("Ciudad")["Edad"].mean())

'\nLa función `groupby()` en Pandas permite agrupar filas de un DataFrame según los valores de una o más columnas, y luego aplicar operaciones de agregación sobre cada grupo.\n\n#### Parámetros principales\n- by (string o lista): columna(s) por las que se quiere agrupar.  \n- aggfunc (función de agregación): operación que se aplica a cada grupo (ejemplo: `mean`, `sum`, `count`, etc.).\n\n### Operaciones comunes con `groupby`\n\nDespués de agrupar con `df.groupby()`, se pueden aplicar distintas funciones de agregación:\n\n- mean() → promedio de cada grupo  \n- sum() → suma de valores  \n- count() → número de elementos en cada grupo  \n- min() / max() → mínimo y máximo de cada grupo  \n- median() → mediana de cada grupo  \n- std() / var() → desviación estándar y varianza  \n- first() / last() → primer o último valor de cada grupo  \n- agg() → aplicar múltiples funciones a la vez  \n    Ejemplo: df.groupby("Ciudad")["Edad"].agg(["mean", "max", "min"])\n'

## 6. Manejo de valores faltantes

In [61]:
# Chequeo de valores nulos
df.isna().sum()

ID                     0
Edad                   0
IngresoMensual         0
GastosMensuales        0
Genero                 0
EstadoCivil            0
Ciudad                 0
TieneTarjetaCredito    0
TieneCuentaAhorro      0
NivelEducacion         0
NumeroComprasMes       0
PuntuacionFidelidad    0
TipoCliente            0
CanalPreferido         0
ProductoFavorito       0
ClienteActivo          0
MayorDe30              0
dtype: int64

In [62]:
# Chequeo de valores nulos
df.isna().sum().sum()

np.int64(0)

In [63]:
# Valores nulos
df2 = pd.DataFrame({"A":[1, None, 3], "B":[4, 5, None]})

print("\nValores nulos:\n", df2.isnull())

Valores nulos:
        A      B
0  False  False
1   True  False
2  False   True

In [64]:
# Eliminar nulos
print("\nEliminar nulos:\n", df2.dropna())
df=df.dropna()  # actualizar df sin nulos

Eliminar nulos:
      A    B
0  1.0  4.0

In [65]:
# Rellenar nulos
print("\nRellenar nulos:\n", df2.fillna(0))

### Rellenar valores nulos con `fillna`
"""
La función **`fillna()`** en Pandas se utiliza para reemplazar valores nulos (`NaN`) en un DataFrame o Serie.

#### Parámetros principales
- value: valor con el que se reemplazarán los nulos.  
  Puede ser un número, cadena, diccionario o incluso otro objeto.  
- method: método de propagación (`ffill` para rellenar hacia adelante, `bfill` para rellenar hacia atrás).  
- axis: eje sobre el que aplicar el relleno (`0` → filas, `1` → columnas).  
- inplace: si es `True`, modifica el DataFrame original sin crear una copia.

# Rellenar nulos hacia adelante
df2.fillna(method='ffill')

# Rellenar nulos hacia atrás
df2.fillna(method='bfill')

# Rellenar nulos hacia adelante, pero solo 1 valor consecutivo
df2.fillna(method='ffill', limit=1)
"""

Rellenar nulos:
      A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

"\nLa función **`fillna()`** en Pandas se utiliza para reemplazar valores nulos (`NaN`) en un DataFrame o Serie.\n\n#### Parámetros principales\n- value: valor con el que se reemplazarán los nulos.  \n  Puede ser un número, cadena, diccionario o incluso otro objeto.  \n- method: método de propagación (`ffill` para rellenar hacia adelante, `bfill` para rellenar hacia atrás).  \n- axis: eje sobre el que aplicar el relleno (`0` → filas, `1` → columnas).  \n- inplace: si es `True`, modifica el DataFrame original sin crear una copia.\n\n# Rellenar nulos hacia adelante\ndf2.fillna(method='ffill')\n\n# Rellenar nulos hacia atrás\ndf2.fillna(method='bfill')\n\n# Rellenar nulos hacia adelante, pero solo 1 valor consecutivo\ndf2.fillna(method='ffill', limit=1)\n"

## 7. Merge, join y concat

In [66]:
# DataFrame principal
df = pd.DataFrame({
    "Nombre": ["Ana", "Luis", "Carla"],
    "Edad": [23, 35, 29],
    "Ciudad": ["La Paz", "Cochabamba", "Santa Cruz"]
})

# DataFrame adicional
df_extra = pd.DataFrame({
    "Nombre": ["Ana", "Luis"],
    "Salario": [500, 700]
})

In [67]:
# Merge
print("\nMerge:\n", pd.merge(df, df_extra, on="Nombre"))

Merge:
   Nombre  Edad      Ciudad  Salario
0    Ana    23      La Paz      500
1   Luis    35  Cochabamba      700

In [68]:
# Concat
print("\nConcat:\n", pd.concat([df, df], axis=0))

Concat:
   Nombre  Edad      Ciudad
0    Ana    23      La Paz
1   Luis    35  Cochabamba
2  Carla    29  Santa Cruz
0    Ana    23      La Paz
1   Luis    35  Cochabamba
2  Carla    29  Santa Cruz

## 8. Lectura y escritura

In [69]:
# Guardar DataFrame a CSV
df.to_csv("archivo.csv", index=False)   # guardar CSV

## 9. Reindexación y renombrar

In [70]:
# Reindexación y renombrar
df = pd.DataFrame({"A":[1,2,3], "B":[4,5,6]}, index=["x","y","z"])
print("\nSin reindexar:\n", df)
print("\nReindexar:\n", df.reindex(["z","y","x","w"]))  # agrega índice faltante

Sin reindexar:
    A  B
x  1  4
y  2  5
z  3  6

Reindexar:
      A    B
z  3.0  6.0
y  2.0  5.0
x  1.0  4.0
w  NaN  NaN

In [71]:
# Renombrar columnas
# Renombrar y guardar
df = df.rename(columns={"A": "Columna1"})
print("\nRenombrar columnas:\n", df)

Renombrar columnas:
    Columna1  B
x         1  4
y         2  5
z         3  6

## 10. Funciones de texto

In [72]:
# Operaciones con texto
df_text = pd.DataFrame({"Nombres":["Ana","Luis","Carla"]})
print("\nNombres originales:\n", df_text["Nombres"])
print("\nMayúsculas:\n", df_text["Nombres"].str.upper())
df_text["Nombres"]=df_text["Nombres"].str.upper()

Nombres originales:
 0      Ana
1     Luis
2    Carla
Name: Nombres, dtype: object

Mayúsculas:
 0      ANA
1     LUIS
2    CARLA
Name: Nombres, dtype: object

In [73]:
# Convertir a minúsculas
print("\nMinúsculas:\n", df_text["Nombres"].str.lower())

Minúsculas:
 0      ana
1     luis
2    carla
Name: Nombres, dtype: object

In [74]:
# Contiene 'a'
print("\nContiene 'a':\n", df_text["Nombres"].str.contains("a"))

Contiene 'a':
 0    False
1    False
2    False
Name: Nombres, dtype: bool

## 11. Funciones de fechas

In [75]:
# Operaciones con fechas
fechas = pd.date_range("2024-01-01", periods=5, freq="D")
print("\nFechas:\n", fechas)

df_fechas = pd.DataFrame({"Fecha":fechas})
print("\nFechas DataFrame:\n", df_fechas)

Fechas:
 DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05'],
              dtype='datetime64[ns]', freq='D')

Fechas DataFrame:
        Fecha
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

In [76]:
# Año y mes de las fechas
print("\nAño de cada fecha:\n", df_fechas["Fecha"].dt.year)
print("\nMes de cada fecha:\n", df_fechas["Fecha"].dt.month)

Año de cada fecha:
 0    2024
1    2024
2    2024
3    2024
4    2024
Name: Fecha, dtype: int32

Mes de cada fecha:
 0    1
1    1
2    1
3    1
4    1
Name: Fecha, dtype: int32

## 12. Funciones estadísticas

In [77]:
# Estadísticas descriptivas
df_num = pd.DataFrame({"Valores":[10,20,30,40,50]})
print("\nMedia:\n", df_num["Valores"].mean())
print("\nMediana:\n", df_num["Valores"].median())
print("\nVarianza:\n", df_num["Valores"].var())
print("\nCorrelación:\n", df_num.corr())

Media:
 30.0

Mediana:
 30.0

Varianza:
 250.0

Correlación:
          Valores
Valores      1.0

## 13. Funciones de Pivot y tablas

In [78]:
# -------------------------------
# Ejemplo de tabla pivote en pandas
# -------------------------------

# Crear un DataFrame con información de ventas
df_pivot = pd.DataFrame({
    "Ciudad": ["La Paz", "La Paz", "Cochabamba", "Santa Cruz"],  # Categoría principal
    "Año": [2023, 2024, 2023, 2024],                            # Variable que se convertirá en columnas
    "Ventas": [100, 150, 200, 250]                              # Valores a agregar
})
print("\nDataFrame original:\n", df_pivot)

# Crear la tabla pivote
# values  : columna numérica que se va a resumir
# index   : filas de la tabla pivote
# columns : columnas de la tabla pivote
# aggfunc : función de agregación (por defecto es la media)
tabla_pivote = pd.pivot_table(
    df_pivot,
    values="Ventas",
    index="Ciudad",
    columns="Año"
)

# Mostrar el resultado
print("\nTabla pivote:\n", tabla_pivote)

DataFrame original:
        Ciudad   Año  Ventas
0      La Paz  2023     100
1      La Paz  2024     150
2  Cochabamba  2023     200
3  Santa Cruz  2024     250

Tabla pivote:
 Año          2023   2024
Ciudad
Cochabamba  200.0    NaN
La Paz      100.0  150.0
Santa Cruz    NaN  250.0

## 14. Funciones de ventana

In [79]:
# Media móvil (rolling mean)

# Crear un DataFrame numérico de ejemplo
df_num = pd.DataFrame({
    "Valores": [9, 22, 31, 47, 59, 60]
})

# Calcular la media móvil
# window=3 indica que el promedio se calcula usando
# los últimos 3 valores consecutivos
media_movil = df_num["Valores"].rolling(window=3).mean()

# Mostrar el resultado
print("\nMedia móvil:\n", media_movil)

Media móvil:
 0          NaN
1          NaN
2    20.666667
3    33.333333
4    45.666667
5    55.333333
Name: Valores, dtype: float64

In [80]:
# Suma acumulada (cumulative sum)
print("\nSuma acumulada:\n", df_num["Valores"].cumsum())

Suma acumulada:
 0      9
1     31
2     62
3    109
4    168
5    228
Name: Valores, dtype: int64

## 15. Funciones de categorías

In [81]:
# Operaciones con datos categóricos
df_cat = pd.DataFrame({"Colores":["Rojo","Azul","Rojo","Verde"]})
print(df_cat)

df_cat["Colores"] = df_cat["Colores"].astype("category")
print("\nCategorías:\n", df_cat["Colores"].cat.categories)

print("\nCodificación numérica:\n", df_cat["Colores"].cat.codes)

  Colores
0    Rojo
1    Azul
2    Rojo
3   Verde

Categorías:
 Index(['Azul', 'Rojo', 'Verde'], dtype='object')

Codificación numérica:
 0    1
1    0
2    1
3    2
dtype: int8